### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by haddung** [f0y/due_date_reminder#17]
Hi!

I've installed the Due Date Reminder Plugin on my 2.1. Redmine. Accroding to http://www.redmine.org/plugins/due_date_reminder it should be compatible with 2.1.

But after installing, migrate and restarting I get a 500 Error after Login.

The log states :

Started GET "/redmine/my/page" for 84.00.00.172 at Wed Oct 03 13:45:01 +0200 2012
Processing by MyController#page as HTML
Current user: admin (id=1)
Rendered issues/_list_simple.html.erb (10.0ms)
Rendered my/blocks/_issuesassignedtome.html.erb (227.0ms)
Rendered issues/_list_simple.html.erb (30.0ms)
Rendered my/blocks/_issuesreportedbyme.html.erb (156.0ms)
Rendered my/page.html.erb within layouts/base (1151.1ms)
Completed 500 Internal Server Error in 1624ms

ActionView::Template::Error (undefined method association_class' for nil:NilClass): 
33 <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if controller.default_search_scope %> 
34: <label for='q'> 
35: <%= link_to l(:label_search), {:controller => 'search', :action => 'index', :id => @project}, :accesskey => accesskey(:search) %>: 
36: </label> 
37: <%= text_field_tag 'q', @question, :size => 20, :class => 'small', :accesskey => accesskey(:quick_search) %> 
38: <% end %> 
39: <%= render_project_jump_box %>

app/helpers/application_helper.rb:268:inrender_project_jump_box' app/views/layouts/base.html.erb:36:in `_app_views_layouts_base_html_erb___201915114_99968940'

I have also tried the solution mentioned here: http://www.redmine.org/boards/3/topics/30930?r=30973#message-30973

Any suggestions here? Thank you!

**Comment by f0y** [comment]
Hi!

Do you have any other plugins installed? What is an output of a command
`git branch` (perform it in due_date_reminder directory)?

On Fri, Oct 5, 2012 at 2:17 AM, haddung notifications@github.com wrote:

> Hi!
> 
> I've installed the Due Date Reminder Plugin on my 2.1. Redmine. Accroding
> to http://www.redmine.org/plugins/due_date_reminder it should be
> compatible with 2.1.
> 
> But after installing, migrate and restarting I get a 500 Error after Login.
> 
> The log states :
> 
> Started GET "/redmine/my/page" for 84.00.00.172 at Wed Oct 03 13:45:01
> +0200 2012
> Processing by MyController#page as HTML
> Current user: admin (id=1)
> Rendered issues/_list_simple.html.erb (10.0ms)
> Rendered my/blocks/_issuesassignedtome.html.erb (227.0ms)
> Rendered issues/_list_simple.html.erb (30.0ms)
> Rendered my/blocks/_issuesreportedbyme.html.erb (156.0ms)
> Rendered my/page.html.erb within layouts/base (1151.1ms)
> Completed 500 Internal Server Error in 1624ms
> 
> ActionView::Template::Error (undefined method association_class' for
> nil:NilClass):
> 33 <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if
> controller.default_search_scope %>
> 34:
> 35: <%= link_to l(:label_search), {:controller => 'search', :action =>
> 'index', :id => @project https://github.com/project}, :accesskey =>
> accesskey(:search) %>:
> 36:
> 37: <%= text_field_tag 'q', @question https://github.com/question,
> :size => 20, :class => 'small', :accesskey => accesskey(:quick_search) %>
> 38: <% end %>
> 39: <%= render_project_jump_box %>
> 
> app/helpers/application_helper.rb:268:inrender_project_jump_box'
> app/views/layouts/base.html.erb:36:in `_app_views_layouts_base_html_erb_
> __201915114_99968940'
> 
> I have also tried the solution mentioned here:
> http://www.redmine.org/boards/3/topics/30930?r=30973#message-30973
> 
> Any suggestions here? Thank you!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/due_date_reminder/issues/17.

## 

Best Wishes,
Oleg Kandaurov

**Comment by haddung** [comment]
Hi!
I deleted all other plugins to be sure it's a problem with Due Date Reminder.
The comand brings following output:

C:\REDMINE\apps\redmine\htdocs\plugins\redmine_due_date_reminder>git branch
fatal: Not a git repository (or any of the parent directories): .git

I downloaded the .zip to install the plugin...

**Comment by f0y** [comment]
I suppose You have a wrong version of the plugin. Please install it from the link below https://github.com/f0y/due_date_reminder/zipball/redmine-2.1

**Comment by haddung** [comment]
I installed from your link and did "bundle install" afterwards. When I tried migrate the following error occurred:

C:\REDMINE\apps\redmine\htdocs\plugins>rake redmine:plugins:migrate RAILS_ENV=pr
oduction --trace
(in C:/REDMINE/apps/redmine/htdocs)
rake aborted!
Incorrect MySQL client library version! This gem was compiled for 6.0.0 but the
client library is 5.0.83.
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2/1.8/
mysql2.so
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2/mysq
l2.rb:2
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2.rb:9
:in `require'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2.rb:9

C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:
in `require'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:
in`require'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:
in `each'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:
in`require'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:
in `each'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:
in`require'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/bundler-1.0.21/lib/bundler.rb:122:in `req
uire'
C:/REDMINE/apps/redmine/htdocs/config/application.rb:7
C:/REDMINE/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_ori
ginal_require'
C:/REDMINE/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require
'
C:/REDMINE/apps/redmine/htdocs/Rakefile:5
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:i
n`load'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:i
n `load_rakefile'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:501:
in`raw_load_rakefile'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:82:i
n `load_rakefile'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:
in`standard_exception_handling'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:81:i
n `load_rakefile'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:65:i
n`run'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:
in `standard_exception_handling'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:i
n`run'
C:/REDMINE/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
C:/REDMINE/ruby/bin/rake:19:in `load'
C:/REDMINE/ruby/bin/rake:19

**Comment by f0y** [comment]
I believe that there are some diffucties with running plugin on ruby 1.8 according to that guy https://github.com/theonlyulti/due_date_reminder. Try to remove `test` directory and Gemfile and Gemfile.lock from plugin directory. 

And you must not do `bundle install` in plugin directory.

**Comment by haddung** [comment]
I am now able to install the plugin! Thank you very much!
But when I try to configured the plugin it tries to access:  
   http://mydomain/redmine/settings/plugin/due_date_reminder and I get a 404 error!

**Comment by f0y** [comment]
Something wrong with your redmine  configuration then. Good luck!

On Fri, Oct 5, 2012 at 3:14 PM, haddung notifications@github.com wrote:

> I am now able to install the plugin! Thank you very much!
> But when I try to configured the plugin it tries to access:
> 
> http://mydomain/redmine/settings/plugin/due_date_reminder and I get a 404
> error!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/due_date_reminder/issues/17#issuecomment-9172244.

## 

Best Wishes,
Oleg Kandaurov

**Comment by haddung** [comment]
Why? Where do I have to look? What should the link be?

**Comment by f0y** [comment]
Simply because it is completely Redmine responsibility to create that link
properly.
It is hard to say where you should look. Maybe something wrong with
webserver configuration. I do not have much experience
with setting up Redmine.

On Fri, Oct 5, 2012 at 4:44 PM, haddung notifications@github.com wrote:

> Why? Where do I have to look? What should the link be?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/due_date_reminder/issues/17#issuecomment-9174108.

## 

Best Wishes,
Oleg Kandaurov

**Comment by f0y** [comment]
Btw, link is correct. Webserver can not find this page.

**Comment by haddung** [comment]
All right, thanks for your help! I will try to figure this out!

**Comment by haddung** [comment]
According to the guys at the bitnami forums, it's a plugin issue...

http://answers.bitnami.org/questions/7563/redmine-due-date-reminder-plugin-500-internal-error

**Comment by Ipaulsen** [comment]
I have been getting this error while trying to go to the log in page, just happened haven't changed-ed anything as far as versions... tried to follow the thread, but a little confused :(

error log below

app/views/layouts/base.html.erb:37:in `_app_views_layouts_base_html_erb___695339911_32923608'

Started GET "/redmine/login" for ..**_.**_ at 2013-06-27 11:17:13 -0600
Processing by AccountController#login as HTML
Current user: ipaulsen (id=1)
Redirected to http://**_.**_._**.__/redmine/
Completed 302 Found in 0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/" for .._**.**\* at 2013-06-27 11:17:13 -0600
Processing by WelcomeController#index as HTML
Current user: *\* (id=1)
Rendered welcome/index.html.erb within layouts/base (0.0ms)
Completed 500 Internal Server Error in 31ms

ActionView::Template::Error (undefined local variable or method render_projects_jump_box' for #<#Class:0x3f1dcb8:0x3e74758>):
34: <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if controller.default_search_scope >
35: <label for='q'>
36: <= link_to l(:label_search), {:controller => 'search', :action => 'index', :id => @projects}, :accesskey => accesskey(:search) >:
37: </label>
38: <= text_field_tag 'q', @question, :size => 20, :class => 'small', :accesskey => accesskey(:quick_search) >
39: < end >
40: <= render_projects_jump_box %>
app/views/layouts/base.html.erb:37:in_app_views_layouts_base_html_erb___695339911_32923608'

thanks, please help!
