### ISSUE TITLE
NO e-mail is send

### ISSUE THREAD

**Issue by haddung** [f0y/due_date_reminder#19]
Hi!

I installed your plugin and created an issue which is assigned to my user.
But even when the due date is within the specified days I don't receive any e-mail.

What am I doing wrong?
Is there a way to find out where the problem is located?
Thanks in advance!

**Comment by f0y** [comment]
You should check whether a test emails are sent or not. It can be done in administration menu.

**Comment by haddung** [comment]
The test email and the notifications for new issues are sent without any problem...

**Comment by f0y** [comment]
It's probably an issue related to compatibility Redmine and the plugin. What redmine version did you install? And how did you install plugin itself?

**Comment by haddung** [comment]
Thanks for your reply!
I am using Redmine 2.1.2.

The plugin was installed like I mentioned here:
http://answers.bitnami.org/questions/7563/redmine-due-date-reminder-plugin-500-internal-error

" I cloned form git and removed the gem file. Then migrate in the htdcos directory and restarted everything! "

**Comment by haddung** [comment]
Any idea what could be wrong? Thanks!

**Comment by f0y** [comment]
Sorry, I do not know. Maybe it does not work at all and you are the first
who noticed it. Is there abything in the logs?

On Thu, Nov 8, 2012 at 9:51 PM, haddung notifications@github.com wrote:

> Any idea what could be wrong? Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/due_date_reminder/issues/19#issuecomment-10197707.

## 

Best Wishes,
Oleg Kandaurov

**Comment by haddung** [comment]
Hi!

Is it working with your Redmine version?
Which log do you mean?

**Comment by haddung** [comment]
And at which time are the mails send?
Is the task performed once a day? And at which time exactly?

**Comment by haddung** [comment]
Anything new?
