### ISSUE TITLE
Mails are not sent by the cron job

### ISSUE THREAD

**Issue by Guite** [f0y/due_date_reminder#22]
Hi,

if I change into my redmine directory and call:

```
bundle exec rake redmine:reminder_plugin:send_notifications RAILS_ENV=production
```

then the email is sent correctly.

But when using the cronjob it does not work.

```
0 5 * * * RedmineUser cd /var/.../redmine/redmine; rake redmine:redminder_plugin:send_notifications RAILS_ENV="production" &> /tmp/redmine_due_date_reminder.log
```

Any idea what we can try to find out the problem cause?

**Comment by assist-software** [comment]
Check the errors from /tmp/redmine_due_date_reminder.log

I had to add path to bins

**Comment by Guite** [comment]
Fixed by changing the syntax to:

```
0 5 * * * RedmineUser cd /var/.../redmine/redmine; rake redmine:send_reminders RAILS_ENV="production"
```

The actual task name (send_reminders) I found with _rake -T_.

**Comment by f0y** [comment]
`rake redmine:send_reminders` is not plugin task. It's built in redmine functionality.

Cron job does not work because of misprint in word `reminder` in command `rake redmine:redminder_plugin:send_notifications`.

**Comment by Guite** [comment]
Thanks for bringing this up! :+1:

**Comment by Guite** [comment]
Works! Thanks again.

**Comment by matbott** [comment]
I have the same problem. my cron line: cd / opt / bitnami / apps / htdocs; rake redmine: send_reminders RAILS_ENV = "production"

Log cron:
rake redmine: send_reminders RAILS_ENV = "production")
November 8 11:21:01 linux CRON [32050]: (root) MAIL (mailed 1 byte of output, but got status 0x004b, # 012)

Any suggestions?
