### ISSUE TITLE
does not work on redmine 2.2.0 redmine trunk

### ISSUE THREAD

**Issue by cforce** [f0y/due_date_reminder#24]
[rake --prereqs] rake aborted!
due_date_reminder plugin requires one the following Redmine versions: 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9 but current is 2.2.0.devel

**Comment by f0y** [comment]
Thank you for report. I will check compatibility with version 2.2
03.01.2013 19:18 пользователь "Terence Miller" notifications@github.com
написал:

**Comment by tzieleniewski** [comment]
Hi,
Any dates for 2.2 compatible version.
Cheers
Tomasz

**Comment by f0y** [comment]
I'm not sure how much time i'll have on the next week.
But uou can try to delete following line from init.rb and restart redmine.

requires_redmine :version => ['2.1.0', '2.1.1', '2.1.2', '2.1.3', '2.1.4',
'2.1.5', '2.1.6', '2.1.7', '2.1.8', '2.1.9']

I hope that 2.2 redmine is backward compatible with 2.1 and plugin will run
without any modifications.
Please let me know about results.

On Fri, Jan 11, 2013 at 4:08 PM, tzieleniewski notifications@github.comwrote:

> Hi,
> Any dates for 2.2 compatible version.
> Cheers
> Tomasz
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/due_date_reminder/issues/24#issuecomment-12141675.

## 

Best Wishes,
Oleg Kandaurov

**Comment by maiklindner** [comment]
Works fine with Redmine 2.2.1.stable. You only have to comment out the line f0y mentioned. Thank you!

**Comment by cforce** [comment]
fixed
