### ISSUE TITLE
rake send_notifications not sending mails

### ISSUE THREAD

**Issue by anibalsanchez** [f0y/due_date_reminder#8]
Hi,

I'm trying to solve why the mails are not coming through. Please, check this:

rake redmine:reminder_plugin:send_notifications RAILS_ENV=production --trace
*\* Invoke redmine:reminder_plugin:send_notifications (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:reminder_plugin:send_notifications

In the log, I can verify:

Connecting to database specified by database.yml
OpenIdAuthentication.store is nil. Using in-memory store.
Creating scope :active. Overwriting existing method User.active.
Creating scope :open. Overwriting existing method Version.open.
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in CollectiveIdea::Acts::NestedSet::Model instead. (called from include at /home/projec12/redmine-2.0.2/lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:58)
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in CollectiveIdea::Acts::NestedSet::Model instead. (called from include at /home/projec12/redmine-2.0.2/lib/plugins/awesome_nested_set/lib/awesome_nested_set/awesome_nested_set.rb:58)
Creating scope :open. Overwriting existing method Issue.open.
  Rendered plugins/due_date_reminder/app/views/reminder_mailer/due_date_notification.text.erb within layouts/mailer (37.8ms)
  Rendered plugins/due_date_reminder/app/views/reminder_mailer/due_date_notification.html.erb within layouts/mailer (1.4ms)

However.... no mail.... do you have any tip?

Regards,
Anibal

**Comment by f0y** [comment]
Maybe you do not have issues with proper due date, do you?
There is nothing wrong in logs...

**Comment by anibalsanchez** [comment]
But it's generating mails.... I've forced in the mailer task to send all
generated mails to me.... but no mail is sent.

I think it's related with rake... but I don't know where to check it.

Thanks,
Anibal

**Comment by f0y** [comment]
How do you know whether it generates emails or not? I do not see any messages in the logs which are related to the generation of the email.

**Comment by anibalsanchez** [comment]
These entries seems to be generated one per each mail:

Rendered plugins/due_date_reminder/app/views/reminder_mailer/due_date_notification.html.erb within layouts/mailer

**Comment by f0y** [comment]
Unfortunately I have no idea what is wrong. But You can try to disable asynchronous mail deliviery, it might help...
What version of Redmine and the plugin do you use?
Probably, I will check this issue on next weekends.

**Comment by anibalsanchez** [comment]
I'm running the last version v2.0.3.

I'm going to try to solve it tomorrow.

Thanks

**Comment by anibalsanchez** [comment]
We solved the issue.

We are running the task in development mode with smtp.

Production site works with no problem using sendmail.... however rake
requires smtp to work.... very very odd.

Thanks,
Anibal

**Comment by f0y** [comment]
Ok. I think the issue is closed

**Comment by anibalsanchez** [comment]
Yeah, Thanks!
